$fn=250;
BASE = 15;
BASE_WALL = 3;
INSIDE_DIAMETER = 7;
GAP = 2.5;
CYLINDER_WALL = 2;
CYLINDER_LENGTH = 15;





union()
{
	difference()
	{
		cylinder(h = CYLINDER_LENGTH, d = INSIDE_DIAMETER + 2*CYLINDER_WALL);
		cylinder(h = CYLINDER_LENGTH, d = INSIDE_DIAMETER);
		translate([-INSIDE_DIAMETER/2-CYLINDER_WALL,1,0])cube([INSIDE_DIAMETER-2,GAP,CYLINDER_LENGTH]);

	}
	translate([-BASE/2,INSIDE_DIAMETER/2,0])cube([BASE, BASE_WALL, CYLINDER_LENGTH+2*GAP+BASE]);

	
}