$fn = 50;
LENGTH = 40;
HEIGHT = 20;
WALL = 3;

INSIDE_HEIGHT = 10;
GAP = 1.5;

cube([WALL, LENGTH, HEIGHT]);
translate([WALL,0,0])cube([INSIDE_HEIGHT, LENGTH, WALL]);
translate([WALL+INSIDE_HEIGHT,0,0])cube([WALL, LENGTH, INSIDE_HEIGHT+WALL]);
translate([WALL+GAP,0,WALL+INSIDE_HEIGHT])cube([INSIDE_HEIGHT+GAP, LENGTH, WALL]);